import Providers from "./Providers";
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Create Next App - Test",
  description: "Generated by create next app",
};

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
